### ISSUE TITLE
Some reason dosent skip the lesson.

### ISSUE THREAD

**Issue by masssydoosy** [cupiditys/iReady-Overload#8] opened 2021-11-22 21:05 UTC
So i did everything correctly On EDGE and i tested it and it somehow did not work, and it is the newest one says Cupiditys (Github) can you help me out its painful not skipping it.

**Comment by cupiditys** [comment] 2021-11-22 21:28
yes, i am on my way back home i committed the wrong version yesterday so the lesson skipper does not work rn

**Comment by masssydoosy** [comment] 2021-11-22 21:29
k

**Comment by cupiditys** [comment] 2021-11-22 21:44
turns out its a slightly worse issue, its throwing 401 unauthorized errors now

**Comment by masssydoosy** [comment] 2021-11-22 21:45
uh oh

**Comment by cyber1109** [comment] 2021-11-22 21:53
> turns out its a slightly worse issue, its throwing 401 unauthorized errors now

so how bad is that

**Comment by cyber1109** [comment] 2021-11-22 21:56
idk how BUT I WILL DO EVERYTHING IN MY POWER TO HELP I GOT 25$ AND A STONG WILL AND 4 LESSONS ON IREADY DUE TODAY SO I WILL HELP AT ENYCOST

**Comment by masssydoosy** [comment] 2021-11-22 22:00
damn 4 lessons every day?! i hope you like break iready system forever

**Comment by cyber1109** [comment] 2021-11-22 22:01
i get 510 coin's every week

**Comment by cyber1109** [comment] 2021-11-22 22:02
its sad

**Comment by masssydoosy** [comment] 2021-11-22 22:02
i do 2 per day

**Comment by masssydoosy** [comment] 2021-11-22 22:03
no breaks :9

**Comment by cyber1109** [comment] 2021-11-22 22:03
i have to fight 5 bears everyday to get to school

**Comment by cupiditys** [comment] 2021-11-22 22:05
> > turns out its a slightly worse issue, its throwing 401 unauthorized errors now
> 
> so how bad is that

depends

**Comment by cupiditys** [comment] 2021-11-22 22:06
rn it seems to me they made the authorization and request-id headers required

**Comment by cyber1109** [comment] 2021-11-22 22:06
ok how can i help

**Comment by cyber1109** [comment] 2021-11-22 22:10
> rn it seems to me they made the authorization and request-id headers required

so it wont be done today

**Comment by cupiditys** [comment] 2021-11-22 22:11
probably not, this is kinda weird. it says 'You are not authorized to access this resource.' when you try

**Comment by cyber1109** [comment] 2021-11-23 02:48
hows it going

**Comment by cyber1109** [comment] 2021-11-23 02:49
u got discord

**Comment by SomeGuy3332** [comment] 2021-11-23 03:32
Yea i tried it today and it allows me to hit the lesson skip but when i close the lesson nothing happens im pretty sure they patched it, hopefully you can get it fixed soon

**Comment by cupiditys** [comment] 2021-11-23 14:04
i know how to fix it but im at school and can't do it until later sadly

**Comment by sneak599** [comment] 2021-11-23 14:19
bro you a saint

**Comment by cyber1109** [comment] 2021-11-24 00:40
> i know how to fix it but im at school and can't do it until later sadly
is it done

**Comment by cyber1109** [comment] 2021-11-24 00:43
> i know how to fix it but im at school and can't do it until later sadly

i got 10 lesoons due by tmr can you get it done by then

**Comment by sneak599** [comment] 2021-11-24 00:43
> > i know how to fix it but im at school and can't do it until later sadly
> 
> i got 10 lesoons due by tmr can you get it done by then

yeah its not working rn got three

**Comment by cyber1109** [comment] 2021-11-24 00:45
> > > i know how to fix it but im at school and can't do it until later sadly
> > 
> > 
> > i got 10 lesoons due by tmr can you get it done by then
> 
> yeah its not working rn got three

not to be dumb but whats 3 mean

**Comment by cupiditys** [comment] 2021-11-24 01:58
i know how to fix it and have, but the problem is it doesnt work as a chrome extension

**Comment by cupiditys** [comment] 2021-11-24 01:58
im trying to find a way to do it

**Comment by cyber1109** [comment] 2021-11-24 19:46
> i know how to fix it and have, but the problem is it doesnt work as a chrome extension
I DONT NEED IT AS CROME EXTESON RN PLEES RELES IT

**Comment by cyber1109** [comment] 2021-11-24 19:46
i have 5 more lessons do in 1 hour

**Comment by cyber1109** [comment] 2021-11-24 23:01
HELLLLLLPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP

**Comment by cyber1109** [comment] 2021-11-25 00:00
PLEESSS

**Comment by cyber1109** [comment] 2021-11-26 18:51
> > i know how to fix it but im at school and can't do it until later sadly
> 
> Ok its been 3 whole days hows the progress?

for  real tho

**Comment by cupiditys** [comment] 2021-11-27 07:19
fixed, https://github.com/cupiditys/iReady-Overload/tree/main/lessonSkipper

**Closed by cupiditys** 2021-11-27 07:19 UTC
